### Variáveis de ambiente
@base_url = http://localhost:3333
@route = messages
@user_id_marcelo = 795161b5-a4a1-418d-891e-48b33f0b2653
@admin_id = dc75e7d5-1622-47a1-bae2-f81ad5bb3cdb


### POST Message user
###  add message 
POST {{base_url}}/{{route}}
Content-Type: application/json

{
  "user_id": "{{user_id_marcelo}}",
  "text": "Olá eu preciso de ajuda!"
}

### POST Message admin to user
###  add message 
POST {{base_url}}/{{route}}
Content-Type: application/json

{
  "user_id_marcelo": "{{user_id_marcelo}}",
  "text": "Olá, boa tarde! Como posso ajudar?",
  "admin_id": "{{admin_id}}"
}

### GET list messages by user
GET  {{base_url}}/{{route}}/{{user_id_marcelo}}
